---
- name: Install LAMP stack [Linux-Apache-MySQL-PHP]
  hosts: centos-lamp-server
  remote_user: vagrant
  become: yes

  roles:
  - apache
  - php
  
- name: Install Nginx
  hosts: ubuntu-nginx-server
  remote_user: vagrant
  become: yes

  roles:
  - nginx