---
# Task file for mysql
- name: Download MySQL Community Repo
  get_url:
    url: https://dev.mysql.com/get/mysql57-community-release-el7-9.noarch.rpm
    dest: /tmp

- name: Install MySQL Community Repo
  command: /usr/bin/rpm -ivh /tmp/mysql57-community-release-el7-9.noarch.rpm
  ignore_errors: yes

- name : Install mysql server
  yum :
    name={{item}}
    state=present
  with_items : "{{mysql_pkgs}}"

- name : Start mysql service
  service : name=mysqld state=started enabled=true

- name: Copy password to file
  command: bash -c "grep 'temporary password' /var/log/mysqld.log | awk '{print $NF}'"
  register: temp_pass 
  changed_when: False
  local_action: copy content: '[client]\n user=root \n password={{temp_pass}}' dest=/root/.my.cnf 

- name : Copy the initial SQL scripts
  copy : src=sql-files/initial.sql dest=/tmp/initial.sql

- name : Create DB & execute sql on the created DB
  mysql_db : name=TUTORIALS state=present

- name : Execute sql on the created DB
  mysql_db : name=TUTORIALS state=import target=/tmp/initial.sql
